/*
 * Music Details
 * A frame for the EMPlayerToolBar
 * Use to show the details of the Music
 * 
 * Sebastian Ko
 * 16/11/2012
 */

package fypaudioplayer;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import net.AudioDetails;
import tag.codec.AudioTAG;

/**
 *
 * @author Ivan
 */
public class musicDetails extends javax.swing.JFrame {
    public boolean isPopup          = false;
    
    private File readSong           = null;
    private AudioDetails readDetails= null;
    
    private String _Title           = "";
    private String _Artist          = "";
    private String _Album           = "";
    private String _Track           = "";
    private Image _Cover            = null;

    /** Creates new form musicDetails */
    public musicDetails(int positionX,int positionY) {
        initComponents();
        this.setLocation(positionX,positionY);
        
        /*//SE 1.7
        this.setOpacity(0.0f);
        this.setBackground(new Color(255, 255, 255, 0));
        /**/
        
        //SE 1.6
        AWTUtilities.setWindowOpacity(this,0.0f);
        AWTUtilities.setWindowOpaque(this, false);
        /**/
        
        this.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cover = new javax.swing.JLabel();
        detailsTitle = new javax.swing.JLabel();
        detailsArtist = new javax.swing.JLabel();
        detailsAlbum = new javax.swing.JLabel();
        detailsTrack = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusableWindowState(false);
        setResizable(false);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        getContentPane().setLayout(null);

        Cover.setFont(new java.awt.Font("微軟正黑體", 1, 11));
        Cover.setForeground(new java.awt.Color(255, 255, 255));
        Cover.setText("Cover");
        getContentPane().add(Cover);
        Cover.setBounds(10, 20, 60, 60);

        detailsTitle.setFont(new java.awt.Font("微軟正黑體", 1, 11));
        detailsTitle.setForeground(new java.awt.Color(255, 255, 255));
        detailsTitle.setText("Title : ");
        getContentPane().add(detailsTitle);
        detailsTitle.setBounds(80, 10, 120, 15);

        detailsArtist.setFont(new java.awt.Font("微軟正黑體", 1, 11));
        detailsArtist.setForeground(new java.awt.Color(255, 255, 255));
        detailsArtist.setText("Artist : ");
        getContentPane().add(detailsArtist);
        detailsArtist.setBounds(80, 30, 120, 15);

        detailsAlbum.setFont(new java.awt.Font("微軟正黑體", 1, 11));
        detailsAlbum.setForeground(new java.awt.Color(255, 255, 255));
        detailsAlbum.setText("Album : ");
        getContentPane().add(detailsAlbum);
        detailsAlbum.setBounds(80, 50, 120, 15);

        detailsTrack.setFont(new java.awt.Font("微軟正黑體", 1, 11));
        detailsTrack.setForeground(new java.awt.Color(255, 255, 255));
        detailsTrack.setText("Track : ");
        getContentPane().add(detailsTrack);
        detailsTrack.setBounds(80, 70, 120, 15);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defaultSkin/dbg.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 200, 100);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-200)/2, (screenSize.height-100)/2, 200, 100);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        if(isPopup){
            try {Thread.sleep(1000);} catch (Exception ex) {}
            Popup(false);
        }
    }//GEN-LAST:event_formMouseExited
    
    public void setSong(File song){
        readSong = song;
        new Thread(new Runnable(){public void run(){
            try {
                AudioTAG songDetails = new AudioTAG(readSong.getPath());
                _Title      = songDetails.getTagTitle();
                _Artist     = songDetails.getTagArtist();
                _Album      = songDetails.getTagAlbum();
                _Track      = songDetails.getTagTrack();
                _Cover      = songDetails.getTagCover();

                if(_Artist == null)_Artist     = "-";
                if(_Album == null)_Album      = "-";
                if(_Track == null)_Track      = "-";
                    
                
                detailsTitle.setText("Title : "+_Title);
                detailsArtist.setText("Artist : "+_Artist);
                detailsAlbum.setText("Album : "+_Album);
                detailsTrack.setText("Track : "+_Track);
                
                if(_Cover != null){
                    _Cover = _Cover.getScaledInstance(60,60, Image.SCALE_SMOOTH);
                    ImageIcon coverIcon = new ImageIcon(_Cover);
                    Cover.setIcon(coverIcon);
                }else
                    Cover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defaultSkin/default-cover.png")));
                
                
                Popup(true);
                try {Thread.sleep(2000);} catch (InterruptedException ex) {}
                Popup(false);
            } catch (Exception ex) {ex.printStackTrace();}
        }}).start();
    }
    
    
    public void setSong(AudioDetails audioDetails){
        readDetails = audioDetails;
        new Thread(new Runnable(){public void run(){
            if(readDetails.containsTag()){
                _Title      = readDetails.getTagTitle();
                _Artist     = readDetails.getTagArtist();
                _Album      = readDetails.getTagAlbum();
                _Track      = readDetails.getTagTrack();
            }

            detailsTitle.setText("Title : "+_Title);
            detailsArtist.setText("Artist : "+_Artist);
            detailsAlbum.setText("Album : "+_Album);
            detailsTrack.setText("Track : "+_Track);

            if(readDetails.containCover()){
                try {
                    _Cover  = readDetails.getTagCover();
                    _Cover = _Cover.getScaledInstance(60,60, Image.SCALE_SMOOTH);
                    ImageIcon coverIcon = new ImageIcon(_Cover);
                    Cover.setIcon(coverIcon);
                } catch (IOException ex) {}
            }else
                Cover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defaultSkin/default-cover.png")));

            Popup(true);
            try {Thread.sleep(2000);} catch (InterruptedException ex) {}
            Popup(false);
        }}).start();
    }
    
    
    

    public void Popup(boolean in){
        if(in && !isPopup){
            this.setVisible(true);
            
            float value = 0.0f;
            while(value < 1.0){
                try {Thread.sleep(20);} catch (Exception ex) {}
                //this.setOpacity(value);        //SE 1.7
                AWTUtilities.setWindowOpacity(this,value);  //SE 1.6u10
                value += 0.1f;
            }
            isPopup = true;
        }else if(isPopup){
            float value = 0.9f;
            while(value >= 0.0){
                try {Thread.sleep(20);} catch (Exception ex) {}
                //this.setOpacity(value);        //SE 1.7
                AWTUtilities.setWindowOpacity(this,value);  //SE 1.6u10
                value -= 0.1f;
            }
            //this.setOpacity(0.0f);    //SE 1.7
            AWTUtilities.setWindowOpacity(this,0.0f);
            this.setVisible(false);
            
            isPopup = false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cover;
    private javax.swing.JLabel background;
    private javax.swing.JLabel detailsAlbum;
    private javax.swing.JLabel detailsArtist;
    private javax.swing.JLabel detailsTitle;
    private javax.swing.JLabel detailsTrack;
    // End of variables declaration//GEN-END:variables
}
