/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * networkDetails.java
 *
 * Created on 2013年2月23日, 下午04:14:19
 */
package fypaudioplayer;

import com.sun.awt.AWTUtilities;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ivan
 */
public class networkDetails extends javax.swing.JFrame {

    /** Creates new form networkDetails */
    public networkDetails(int positionX,int positionY) {
        initComponents();
        
        /*//SE 1.7
        this.setBackground(new Color(255, 255, 255, 0));
        /**/
        
        //SE 1.6
        AWTUtilities.setWindowOpaque(this, false);
        /**/
        
        this.setLocation(positionX,positionY);
    }
    
    public void setStatus(String text){
        netLabel.setText(text);
    }
    
    public void waitToClose(int sec){
        try {
            Thread.sleep(1000*sec);
        } catch (InterruptedException ex) {}
        netLabel.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        netLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        netLabel.setForeground(new java.awt.Color(255, 255, 255));
        netLabel.setPreferredSize(new java.awt.Dimension(400, 12));
        getContentPane().add(netLabel);
        netLabel.setBounds(0, 0, 300, 12);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-300)/2, (screenSize.height-12)/2, 300, 12);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel netLabel;
    // End of variables declaration//GEN-END:variables
}
