/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * errPopUp.java
 *
 * Created on 2013年3月18日, 下午10:55:59
 */
package fyplayer;

import com.sun.awt.AWTUtilities;

/**
 *
 * @author Ivan
 */
public class errPopUp extends javax.swing.JFrame {
    /** Creates new form errPopUp */
    public errPopUp(String value) {
        initComponents();
        errorMsg.setText(value);
        this.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        errorMsg = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Oops!!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(5, 5, 60, 30);

        errorMsg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        errorMsg.setText("Testing Error");
        getContentPane().add(errorMsg);
        errorMsg.setBounds(20, 35, 220, 30);

        backGround.setBackground(new java.awt.Color(204, 255, 255));
        backGround.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        backGround.setOpaque(true);
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 250, 90);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-250)/2, (screenSize.height-90)/2, 250, 90);
    }// </editor-fold>//GEN-END:initComponents

    public void popup(){
        this.setVisible(true);

        float value = 0.0f;
        while(value < 0.9){
            try {Thread.sleep(20);} catch (Exception ex) {}
            //this.setOpacity(value);        //SE 1.7
            AWTUtilities.setWindowOpacity(this,value);  //SE 1.6u10
            value += 0.1f;
        }
        try{Thread.sleep(2000);}catch(Exception e){e.printStackTrace();}
        
        while(value >= 0.0){
            try {Thread.sleep(20);} catch (Exception ex) {}
            //this.setOpacity(value);        //SE 1.7
            AWTUtilities.setWindowOpacity(this,value);  //SE 1.6u10
            value -= 0.1f;
        }
        //this.setOpacity(0.0f);    //SE 1.7
        AWTUtilities.setWindowOpacity(this,0.0f);
        this.setVisible(false);
        this.dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
