/*
 * This is the loading frame which use to pop out 
 * while player is loading with data
 * 
 * Sebastian Ko - 12/03/2013
 * 
 */

/*
 * loadingFrame.java
 *
 * Created on 2013年3月12日, 下午10:17:34
 */
package fyplayer;

import com.sun.awt.AWTUtilities;

/**
 *
 * @author Ivan
 */
public class loadingFrame extends javax.swing.JFrame {
    private static boolean popuped = false;

    /** Creates new form loadingFrame */
    public loadingFrame() {
        initComponents();
        this.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Now Loading....");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 20, 170, 20);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defaultSkins/loading.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 70, 90);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Please wait for a moment");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 50, 160, 15);

        backGround.setBackground(new java.awt.Color(204, 255, 255));
        backGround.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        backGround.setOpaque(true);
        getContentPane().add(backGround);
        backGround.setBounds(0, 0, 260, 90);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-257)/2, (screenSize.height-90)/2, 257, 90);
    }// </editor-fold>//GEN-END:initComponents

    public void popout(){
        if(!popuped){
            popuped = true;
            this.setVisible(true);
            
            float value = 0.0f;
            while(value < 0.9){
                try {Thread.sleep(20);} catch (Exception ex) {}
                //this.setOpacity(value);        //SE 1.7
                AWTUtilities.setWindowOpacity(this,value);  //SE 1.6u10
                value += 0.1f;
            }
        }
    }
    
    public void close(){
        if(popuped){
            float value = 0.8f;
            while(value >= 0.0){
                try {Thread.sleep(20);} catch (Exception ex) {}
                //this.setOpacity(value);        //SE 1.7
                AWTUtilities.setWindowOpacity(this,value);  //SE 1.6u10
                value -= 0.1f;
            }
            //this.setOpacity(0.0f);    //SE 1.7
            AWTUtilities.setWindowOpacity(this,0.0f);
            this.setVisible(false);
            
            popuped = false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backGround;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
