/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegForm.java
 *
 * Created on 2013年5月5日, 下午06:56:47
 */
package fyplayer;

import ClientNet.Client;
import com.sun.awt.AWTUtilities;
import mswmusickernel.MSWMusicKernel;

/**
 *
 * @author Ivan
 */
public class RegForm extends MSWMusicKernel {
    private static Client RegConnect = null;

    /** Creates new form RegForm */
    public RegForm() {
        initComponents();
        
        /*/SE 1.7
        this.setOpacity(0.9f);
        this.setBackground(new Color(255, 255, 255, 0));
        /**/
        
        //SE 1.6 u 10
        AWTUtilities.setWindowOpaque(this, false);
        /**/
        
        RegPanel.setVisible(false);
        StatmentText.setEditable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        UsernameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PswdText = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        RepeatPswdText = new javax.swing.JPasswordField();
        btnReg = new javax.swing.JButton();
        FinalWarningLabel = new javax.swing.JLabel();
        btnDecline1 = new javax.swing.JButton();
        checkPwLabel = new javax.swing.JLabel();
        StatmentPanel = new javax.swing.JPanel();
        ScrollStatment = new javax.swing.JScrollPane();
        StatmentText = new javax.swing.JTextArea();
        btnAccept = new javax.swing.JButton();
        btnDecline = new javax.swing.JButton();
        regBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        RegPanel.setBackground(new java.awt.Color(255, 255, 255));
        RegPanel.setLayout(null);

        jLabel1.setText("Login Name : ");
        RegPanel.add(jLabel1);
        jLabel1.setBounds(39, 46, 100, 14);
        RegPanel.add(UsernameText);
        UsernameText.setBounds(150, 43, 200, 25);

        jLabel2.setText("Password : ");
        RegPanel.add(jLabel2);
        jLabel2.setBounds(40, 90, 100, 20);
        RegPanel.add(PswdText);
        PswdText.setBounds(150, 90, 200, 25);

        jLabel3.setText("Repeat Password : ");
        RegPanel.add(jLabel3);
        jLabel3.setBounds(40, 150, 110, 20);

        RepeatPswdText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RepeatPswdTextMouseClicked(evt);
            }
        });
        RegPanel.add(RepeatPswdText);
        RepeatPswdText.setBounds(150, 150, 200, 25);

        btnReg.setText("Register");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        RegPanel.add(btnReg);
        btnReg.setBounds(40, 240, 80, 23);

        FinalWarningLabel.setBackground(new java.awt.Color(240, 0, 0));
        FinalWarningLabel.setForeground(new java.awt.Color(255, 0, 0));
        FinalWarningLabel.setText("Passwords must around 6-10 charaters.");
        RegPanel.add(FinalWarningLabel);
        FinalWarningLabel.setBounds(40, 210, 380, 20);

        btnDecline1.setText("Decline");
        btnDecline1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecline1ActionPerformed(evt);
            }
        });
        RegPanel.add(btnDecline1);
        btnDecline1.setBounds(120, 240, 90, 23);

        checkPwLabel.setForeground(new java.awt.Color(255, 0, 0));
        RegPanel.add(checkPwLabel);
        checkPwLabel.setBounds(150, 110, 200, 20);

        getContentPane().add(RegPanel);
        RegPanel.setBounds(20, 20, 440, 420);

        StatmentPanel.setBackground(new java.awt.Color(255, 255, 255));
        StatmentPanel.setLayout(null);

        StatmentText.setColumns(20);
        StatmentText.setRows(5);
        StatmentText.setText("1/ Privacy Policy\n\nFinal Year Project Music Player (FYPMusicPlayer) respects \nthe privacy rights of users of this application. No personal\ninformation is required to access this application but where \npersonal information is required to be submitted for certain \npurposes stated in this application, you are required to \nenter true and accurate information.\n \n\n2/ Purpose of collection of personal information\nWhen you using this application, you need not supply any \npersonal information to access or use the application but \nFYPMusicPlayer may collect personal information from you if \nyou register for membership, enroll, or if you request for \nany promotional brochures or materials from FYPMusicPlayer. \n\nPersonal information collected from users of this application \nmay also be used by FYPMusicPlayer to provide application \nbased functions.\n\n\n3/ Safety of personal information\n\nFYPMusicPlayer will make all reasonable efforts to ensure that \nany personal information held by it on this application is stored \nin a secure and safe place. FYPMusicPlayer may use data encryption \non this application in order to enable users to keep browsing \ncertain contents.");
        ScrollStatment.setViewportView(StatmentText);

        StatmentPanel.add(ScrollStatment);
        ScrollStatment.setBounds(10, 11, 420, 370);

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        StatmentPanel.add(btnAccept);
        btnAccept.setBounds(10, 390, 90, 23);

        btnDecline.setText("Decline");
        btnDecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineActionPerformed(evt);
            }
        });
        StatmentPanel.add(btnDecline);
        btnDecline.setBounds(100, 390, 90, 23);

        getContentPane().add(StatmentPanel);
        StatmentPanel.setBounds(20, 20, 440, 420);

        regBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defaultSkins/regBg.png"))); // NOI18N
        getContentPane().add(regBackground);
        regBackground.setBounds(0, 0, 480, 460);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-480)/2, (screenSize.height-460)/2, 480, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        this.StatmentPanel.setVisible(false);
        this.RegPanel.setVisible(true);
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnDeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineActionPerformed
        // TODO add your handling code here:
        try{
            RegConnect.DisconnectCentral();
            RegConnect = null;
        }catch(Exception e){}
        this.dispose();
    }//GEN-LAST:event_btnDeclineActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        // TODO add your handling code here:
        if(new String(this.PswdText.getPassword()).length() < 6 || new String(this.PswdText.getPassword()).length() > 10){
            this.FinalWarningLabel.setText("Fail passwords. Passwords must around 6-10 charaters.");
            return;
        }
        
        RegConnect = new Client(CentralServerIP,17220);
        RegConnect.ConnectCentral();
        
        
        if(new String(this.PswdText.getPassword()).equals(new String(this.RepeatPswdText.getPassword()))){
            int ErrorCode = RegConnect.Registration(this.UsernameText.getText(), new String(this.PswdText.getPassword()));
            if(ErrorCode == -2){
                this.FinalWarningLabel.setText("Registration failed in unexpected Error.");
            }else if(ErrorCode == -1){
                this.FinalWarningLabel.setText("Same login ID registered.");
            }else if(ErrorCode == 0){
                this.FinalWarningLabel.setText("Success! This form will close within 5 sec.");
                new Thread(new Runnable(){public void run(){
                    try{Thread.sleep(5000);}catch(Exception e){}
                    dispose();
                }}).start();
            }
        }else
            this.FinalWarningLabel.setText("Two passwords you had entered were not same.");
        
        RegConnect.DisconnectCentral();
    }//GEN-LAST:event_btnRegActionPerformed

    private void btnDecline1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecline1ActionPerformed
        // TODO add your handling code here:
        try{
            RegConnect.DisconnectCentral();
            RegConnect = null;
        }catch(Exception e){}
        this.dispose();
    }//GEN-LAST:event_btnDecline1ActionPerformed

    private void RepeatPswdTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepeatPswdTextMouseClicked
        // TODO add your handling code here:
        int points = 0;
        if (this.PswdText.getPassword().length < 6 || this.PswdText.getPassword().length >10) {
            checkPwLabel.setText("Invalid Passwords !");
        } else {
            boolean upper = false;
            boolean lower = false;
            boolean number = false;
            for (char c : this.PswdText.getPassword()) {
                if (Character.isUpperCase(c)) {
                    upper = true;
                } else if (Character.isLowerCase(c)) {
                    lower = true;
                } else if (Character.isDigit(c)) {
                    number = true;
                }
            }
            if (upper) {
                points++;
            }
            if (lower) {
                points++;
            }
            if (number) {
                points++;
            }
            
            switch(points){
                case 0: checkPwLabel.setText("Password strength: Very Weak");break;
                case 1: checkPwLabel.setText("Password strength: Weak");break;
                case 2: checkPwLabel.setText("Password strength: Medium");break;
                case 3: checkPwLabel.setText("Password strength: Strong");break;
            }
        }
    }//GEN-LAST:event_RepeatPswdTextMouseClicked

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FinalWarningLabel;
    private javax.swing.JPasswordField PswdText;
    private javax.swing.JPanel RegPanel;
    private javax.swing.JPasswordField RepeatPswdText;
    private javax.swing.JScrollPane ScrollStatment;
    private javax.swing.JPanel StatmentPanel;
    private javax.swing.JTextArea StatmentText;
    private javax.swing.JTextField UsernameText;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnDecline;
    private javax.swing.JButton btnDecline1;
    private javax.swing.JButton btnReg;
    private javax.swing.JLabel checkPwLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel regBackground;
    // End of variables declaration//GEN-END:variables
}
